name: AEM-Prod-Sync-Script

on:
  push:
    branches:
      - master
  repository_dispatch:
    types: [backend_automation]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'repository_dispatch' || github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v2
      - name: Link to Cloud-Manager
        run: if [ -z "$(cat .git/config | grep "cloudmanager")" ]; then git remote add cloudmanager https://${{ secrets.CM_CREDENTIALS }}@git.cloudmanager.adobe.com/woolworthsltd/WOOLWORTHSLTDMRM-p15699/; fi

      ## Master branch update
      - name: Fetch-Branch Master
        run: git fetch --unshallow origin
      - name: Create/checkout Master
        run: git checkout master
      - name: Pull changes from Master
        run: git pull -q origin master
      - name: Push changes from Master to Cloudmanager
        run: git push --tags -f -v cloudmanager master
