# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: AEM-Stage-Build-Script

on:
  push:
    branches:
      - release

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Link to Cloud-Manager
        run: if [ -z "$(cat .git/config | grep "cloudmanager")" ]; then git remote add cloudmanager https://${{ secrets.CM_CREDENTIALS }}@git.cloudmanager.adobe.com/woolworthsgroup/woolworthsgroup/; fi

      ## Release branch update
      - name: Fetch-Branch release
        run: git fetch --unshallow origin
      - name: Create/checkout release
        run: git checkout release
      - name: Pull changes from release
        run: git pull -q origin release
      - name: Push changes from release to cloudmanager
        run: git push -f cloudmanager release